# Odoo Community — Docker Compose (Platinum Tier)
# Start: docker compose -f scripts/odoo_docker_compose.yml up -d
# Stop:  docker compose -f scripts/odoo_docker_compose.yml down
# Logs:  docker compose -f scripts/odoo_docker_compose.yml logs -f odoo

version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: odoo-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo_secure_password   # Change this!
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo:17
    container_name: odoo
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"       # HTTP (Caddy will proxy HTTPS)
      - "8072:8072"       # WebSocket (long polling)
    volumes:
      - odoo-data:/var/lib/odoo
      - ./odoo_addons:/mnt/extra-addons   # Custom addons (optional)
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo_secure_password      # Must match db POSTGRES_PASSWORD
    command: >
      odoo
      --db_host=db
      --db_port=5432
      --db_user=odoo
      --db_password=odoo_secure_password
      --workers=2
      --max-cron-threads=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069/web/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  odoo-db:
    name: odoo-db
  odoo-data:
    name: odoo-data

# ── Notes ─────────────────────────────────────────────────────────────────────
# 1. Change the DB password above (both db + odoo services must match)
# 2. First-run setup: visit http://localhost:8069, create a database
# 3. Set ODOO_URL, ODOO_DB, ODOO_USERNAME, ODOO_PASSWORD in .env
# 4. For HTTPS (production): use odoo_cloud_setup.sh to configure Caddy
